### ISSUE TITLE
Help using Amber

### ISSUE THREAD

**Issue by ddavies1972** [EgeBalci/amber#12]
Hi,

I've downloaded the 32 and 64bit version of Amber for windows, and I have tried packing putty (32 and 64bit) with this command:

amber32 -f putty.exe -build

However when I execute putty_packed.exe it crashes with the following message:

'Firma con problemas:
  Nombre del evento de problema:	APPCRASH
  Nombre de la aplicación:	putty_packed.exe
  Versión de la aplicación:	0.0.0.0
  Marca de tiempo de la aplicación:	00000000
  Nombre del módulo con errores:	StackHash_0a9e
  Versión del módulo con errores:	0.0.0.0
  Marca de tiempo del módulo con errores:	00000000
  Código de excepción:	c000001d
  Desplazamiento de excepción:	0066019a
  Versión del sistema operativo:	6.1.7601.2.1.0.256.1
  Id. de configuración regional:	3082
  Información adicional 1:	0a9e
  Información adicional 2:	0a9e372d3b4ad19135b953a78882e789
  Información adicional 3:	0a9e
  Información adicional 4:	0a9e372d3b4ad19135b953a78882e789

Lea nuestra declaración de privacidad en línea:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0c0a

Si la declaración de privacidad en línea no está disponible, lea la declaración de privacidad sin conexión:
  C:\Windows\system32\es-ES\erofflps.txt'

What am I doing wrong?

Thanks for your time.

**Comment by EgeBalci** [comment]
Can you provide me a sample EXE file for further examination?

**Comment by ddavies1972** [comment]
[allfiles.zip](https://github.com/EgeBalci/amber/files/5704279/allfiles.zip)
I am sending you all the files.

**Comment by EgeBalci** [comment]
It looks like `putty_packed.exe` file executes without a problem in my VMs. I also tested it in an online analysis platform and it successfully runs. Here is the link, https://app.any.run/tasks/93d23d08-71fa-413c-8efc-ad6b6b32af58

The problem you are having may be caused by the third-party applications in your system (such as anti-virus software) interfering with the execution of the packed file. There is nothing I can do in this case.
